### ISSUE TITLE
Feature Suggestion: create a game setting to toggle token self-vison on-off

### ISSUE THREAD

**Issue by paulohdsc** [David-Zvekic/TokensVisible#10]
When a token is checked as ***has vision*** but does not emit light and has no vision distance, the controlling player can view the *self-image* of the token, which can be useful. With Yours Tokens Visible activated, this is not possible, and everything is dark.

It would be nice if there was a setting for the GM to choose between the module behavior or the standard Foundry functionality in that case.

Amazing module, btw! Thanks for your work!

Edit: Foundry 0.7.10 - DnD5e 1.2.4

![Clipboard01](https://user-images.githubusercontent.com/75817094/122978160-91254680-d36c-11eb-9503-c20de4db1210.jpg)

**Comment by David-Zvekic** [comment]
the default Foundry code gives the token a minimum dim vision of 50% of its
own width even if you enter '0'.  I didn't like this being forced on the GM.

You can explicitly enable this on a specific token if you want by giving
that token a dim vision radius of 0.5 rather than 0 (assuming the token is
1 grid square in size). Or a vision of 1, if its a 2 gridsize token.

Please tell me if that achieves the effect you want.

DZ

**Comment by paulohdsc** [comment]
Cool, I hadn't thought about it. Good and simple solution.

Even though this can pose an additional difficulty for GMs who like the default behavior. For example, some modules come with macros, items or settings that bring predefined vision configurations that can be turned on or off. These settings would have to be reconfigured if the GM wanted to simulate that 50% minimum dim vision, and it would be difficult to change from one behavior to another.

Despite that, I later checked that you kept the default behavior in version 0.8, which I intend to use from now on. So I'm happy with the answer. You can close the issue if you like.

Thanks for your reply and your time!

Edit: clarification

**Comment by David-Zvekic** [comment]
I actually didn't deliberately keep the behavior in 0.8.  Something else in
0.8 is making the token visible even when they have a 0 vision range and I
don't know what it is yet.

If I ever figure it out, and I change anything, I'll probably make it a
setting called "Tokens See Self"   So, if set ON, then tokens can always
see themself regardless of lighting or vision range.

**Comment by David-Zvekic** [comment]
2.6.0 has implemented Blind Tokens Controllable.
If turned to 'NO' causes tokens without vision to not be able to see themselves or be controlled by players.
If 'YES' then a player can control a token with no vision and see it's position on the map.
This is independant of the actual range of the token vision.  And it depends on the scene requiring Token Vision.
This implements the feature the way I want it.
