### ISSUE TITLE
SightLayer.computeSight is deprecated since FVTT 0.8.2

### ISSUE THREAD

**Issue by dev7355608** [David-Zvekic/TokensVisible#12]

**Comment by manuelVo** [comment]
It's worth noting that while Foundry 0.8 still contains the deprecated SightLayer.computeSight function, that function won't be called anymore. As a result the vision caching done by this module won't take effect until TokensVisible changes over to the new function.

Additionally, Foundry 0.8 does a lot less unnecessary vision recalculations than 0.7 did, so it might be worth revisiting whether vision caching still brings any performance benefit or not.

**Comment by David-Zvekic** [comment]
TokensVisible 2.3.0 now uses the new function in 0.8 and the old one in 0.7

in 0.7 this feature makes a massive difference in scenes with many tokens, and if I fork the code then I wont be able to continue supporting 0.7.x without creating extra work.   

The many of the unnecessary vision recalculations are removed in 0.8, however occasionally the cache still gets a hit, for whatever that's worth.  (maybe not much)  In some cases someone may want to use it.  Possibly if there are a a large number of walls.

thank you for bringing this to my attention.
