### ISSUE TITLE
Invisible token not visible for owner with Levels module

### ISSUE THREAD

**Issue by uniwars** [David-Zvekic/TokensVisible#15]
As the title says, invisible tokens can't be seen by their owner (player) if levels module is also enabled.
Would that be possible to see with level's dev for a compatibility patch for this very sueful feature ?

**Comment by David-Zvekic** [comment]
maybe 2.3.1 is more compatible with levels.  I dont use levels and it seems like a lot of work to set up a test map, but I made some changes that might help.

Can you tell me if this issue has been resolved?

**Comment by uniwars** [comment]
The issue is solved, I can see invisible token as owner :)

Unfortunatly there is a new issue : when moving a token tokens who are not supposed to be seen by levels rules are clipping
I think you can replicate this by having levels (and wall height and better roof for dependencies), make a wall corner with one token at each side and then move the right one from right to left like here : https://prnt.sc/1812r7w
levels aim for the center of a token to see it so at the angle of the corner tokens are supposed to not see each other like that : https://prnt.sc/1812wsj but when moving this token to the right then to the left the other one is clipping for half a second before desappearing as intended

it does the same if one token is supposed to be at another level, he will clip though the roof

Edit : In 2.3 I can't see my token but there is not the clipping bug and in 2.3.1 it's reversed

**Comment by David-Zvekic** [comment]
I appear to be able to replicate this problem with Your Tokens Visible not installed.

I dont believe this issue is related to Your Tokens Visible.

**Comment by uniwars** [comment]
problem seems to be solved with the last patch :)

Edit : just after my post levels updated with a version that had the same problem, idk who fixed what but now it's perfect
