### ISSUE TITLE
Strange bug interaction with Turn Alert

### ISSUE THREAD

**Issue by Iankid** [David-Zvekic/TokensVisible#18]
Hello, so I'm using Turn alert, which attaches to a battle encounter, with a macro to add alerts without open the GUI for it.
For some reason, I was able to single out, the Tokens Visible mod prevents the macro added alerts to appear in the GUI alert list, but still run in the background as expected.
Additionally, even if Token Vision is disabled, after discovery, the issue remained until introducing a new combat encounter

**Comment by David-Zvekic** [comment]
Well I've noticed 1 issue with Turn Alert.  Combatants which are hidden in
the Combat Tracker are also hidden in turn alert, even for the GM. (they
don't appear in the turn alert GUI).  They should appear for the GM so the
GM can set alerts on them.

Beyond that everything seems to be working perfectly for me.  I just tested.

TokensVisible 2.5.1
Foundry 0.8.8
Turn Alert 2.0.0
lib-wrapper 1.7.3.0  (I also tested without lib-wrapper).
alienrpg  2.0.1

I saw nothing in the code that should cause a problem.  And I can't think
of anything that should be be a problem.  There is only 1 time
TokensVisible interacts with the combat tracker and the most that it may do
is set the combattant to hidden. TokensVisible doesn't do anything with the
combat tracker except when creating a new combatant.  And Turn alert in
theory only does something when someone hits 'next turn'.

I can't replicate this issue.

Can you give me more information?

**Comment by Iankid** [comment]
That one issue you noted is it.
I had the combat tracker initial visibility set to hidden.
Guess they can't be hidden for now.

**Comment by Iankid** [comment]
I'm now writing an issue in Turn Alert, as this is more there issue now.

**Comment by David-Zvekic** [comment]
thanks
