### ISSUE TITLE
Shared Vision Incompatibility.

### ISSUE THREAD

**Issue by DarthGecko** [David-Zvekic/TokensVisible#20]
There's libwrapper notification of an incompatibility with the module [Shared Vision](https://github.com/CDeenen/SharedVision). Since you're not updating Push Token Back and merged it with this module, please consider fixing this.

**Comment by David-Zvekic** [comment]
try with version 2.5.2.  Make sure YTV Token MultiVision is set to "Limited" or else you will be directly trying to contradict Shared Vision.   You may need to set some of the other settings to their most-compatible setting in particular Ray Casting Precision, and Sight Calculations Cache. Check the readme.  

Please tell me if that lets you do what you need.
