### ISSUE TITLE
Garbage in release files.

### ISSUE THREAD

**Issue by kimitsu** [David-Zvekic/TokensVisible#22]
There are unnecessary files and folders in the downloaded version of the module:
.\.git\*
.\_MACOSX\*
.\.DS_Store

**Comment by David-Zvekic** [comment]
I know.  is it causing problems?    It's easiest for me to just zip the
directory I use to actually test or else then I'll need to test twice.

**Comment by kimitsu** [comment]
.git is problematic in particular since it may conflict with other repositories. For exxample I keep my whole modules folder as a local repository to keep track of local changes.

**Comment by David-Zvekic** [comment]
I'll figure out something out for future versions. I just needed to know
someone is actually benefiting from this.

**Comment by David-Zvekic** [comment]
2.5.4 and beyond should no longer have the extra files in them
