### ISSUE TITLE
When tokensvisble enabled battle status not available 

### ISSUE THREAD

**Issue by DarkPhonix5097** [David-Zvekic/TokensVisible#26]
When I have runing tokens Visible at version 9 I can not run a battle, cause I can not but Chars in the Battle tracker

**Comment by DarkPhonix5097** [comment]
Only happens when you select add charakters invisible to battle status

**Comment by David-Zvekic** [comment]
this feature should now work again in Foundry 9 as of YTV 2.7.2 Please confirm. (it works for me)
