### ISSUE TITLE
update to v9?

### ISSUE THREAD

**Issue by ctbritt** [David-Zvekic/TokensVisible#27]
Any plans to update this for v9?

**Comment by wmve** [comment]
this module breaks the combat tracker in D35E (by Rughalt).
very sad because i don't have another way to prevent tokens "seeing" things when moved by GM.
really hoping the developer will come back and make an update to align with V9.
please?

**Comment by David-Zvekic** [comment]
combat tracker should work again as of YTV 2.7.2

**Comment by David-Zvekic** [comment]
Your Tokens Visible should be Foundry 0.9 compatible as of 3.0.0
