### ISSUE TITLE
Error when trying tu update module

### ISSUE THREAD

**Issue by uniwars** [David-Zvekic/TokensVisible#28]
Hi, I get this error when trying to update from foundry 
![image](https://user-images.githubusercontent.com/65986545/151695965-77ce7fff-beb9-43d8-9e38-33399bdc87ab.png)

**Comment by Fridan99** [comment]
Same (Foundry 9.245)
![9](https://user-images.githubusercontent.com/86131373/151696616-e016b54f-052a-4000-b26a-e79d852b791d.jpg)

**Comment by thatlonelybugbear** [comment]
The module.json points to the Drag'n'Transfer module instead.

**Comment by thatlonelybugbear** [comment]
If you really need it until @David-Zvekic fixes it you can use this manifest url to install:

https://github.com/thatlonelybugbear/TokensVisible/releases/download/v2.7.2a/module.json


But keep in mind that you'll need to change back to the original manifest url after the fix to get new updates and versions.

**Comment by David-Zvekic** [comment]
oops.. I uploaded the wrong module.json into the release. fixed.

2.7.3 is available now anyway, but I've corrected 2.7.2
