### ISSUE TITLE
Tokens Visible logs continuously console.warn on the players side.

### ISSUE THREAD

**Issue by thatlonelybugbear** [David-Zvekic/TokensVisible#34]
`TokensVisible.js:408` 
`game.users["players"].forEach(f=> {console.warn(f); partyMemberHasPermission = partyMemberHasPermission  ||  tokenTestPerm(token,f,permission);} );`

Removing the `console.warn(f)` fixes

**Comment by David-Zvekic** [comment]
I'll remove it.. it was debug info for me but it serves no purpose anymore.
