### ISSUE TITLE
Hidden tokens shown to players

### ISSUE THREAD

**Issue by amcvfx** [David-Zvekic/TokensVisible#4]
There is an issue with the module in that it shows hidden tokens to players on scenes with Token Vision turned off. I had a location on a world map that I indicated for myself with a hidden token spoiled for the players when they saw it at the start of a session.

**Comment by David-Zvekic** [comment]
I have replicated this.   fix will come in version 1.3.3

**Comment by David-Zvekic** [comment]
1.3.3 is released
