### ISSUE TITLE
Typo in module.json

### ISSUE THREAD

**Issue by Metacomet10** [David-Zvekic/TokensVisible#5]
currently reads 
`"compatibleCoreVeflrsion": "0.7.9",`
Should read
`"compatibleCoreVersion": "0.7.9",`

https://github.com/David-Zvekic/TokensVisible/blob/27e8e338d7b2ea1ea10c7bc9d97c3a8108684b19/module.json#L7

**Comment by David-Zvekic** [comment]
thanks! don't know how that slipped in without causing me any issues. but I'll fix it and investigate later.
