### ISSUE TITLE
Possible conflict between Perfect Vision and Your Tokens Visible

### ISSUE THREAD

**Issue by fel-pt** [David-Zvekic/TokensVisible#6]
I update all my Foundry modules today and started getting a message from libWrapper saying there was a possible conflict between an unknown module and Perfect Vision.

After running a few tests, I realized the unknown module was Your Tokens Visible. This potential conflict wasn't showing up last weekend, so it must have been introduced with Perfect Vision's latest update.

As of right now, I haven't noticed any issue, but I thought I should warn you.

I've also posted about this issue in Perfect Vision's Github: https://github.com/dev7355608/perfect-vision/issues/64

**Comment by David-Zvekic** [comment]
Thanks for the heads up.
Merely using Libwrapper wont provide a solution.
The complexity is that Tokens Visible replaces the raycasting, and it can
be modified at runtime as well as launch time, so it wasn't a
straightforward to me how to use of Libwrapper properly.

I use Perfect Vision in my games, so I will find a way to make both modules
work together, but libwrapper may still complain depending on how I do it.

**Comment by fel-pt** [comment]
Any idea on what issues can be expected? I didn't have time to test a lot of stuff, but they seemed to be working ok with each other.

**Comment by spirritus** [comment]
Have the same issue comming up.

**Comment by dev7355608** [comment]
With libWrapper you are able register and unregister at runtime. Functions you replace you register as OVERRIDE. Then libWrapper shouldn't complain about other wrappers as long there's only one OVERRIDE registered.

From what I can tell the conflict seems to be harmless. If someone notices a problem, I can quickly disable the code in PV that's causing the conflict: it's just a fix of minor bug in core Foundry.

**Comment by David-Zvekic** [comment]
started using libwrapper.  looks like the conflict is resolved.  please tell me how it looks for your end, but from here it looks clean now.

**Comment by fel-pt** [comment]
Looking good here too!
