### ISSUE TITLE
Add libWrapper support

### ISSUE THREAD

**Issue by dev7355608** [David-Zvekic/TokensVisible#7]
This module overrides a bunch of important and popular functions and therefore should use [libWrapper](https://github.com/ruipin/fvtt-lib-wrapper) to avoid conflicts like #6. It doesn't need to a hard dependency, but the module should use libWrapper if it's available.

**Comment by David-Zvekic** [comment]
v1.4.0 started using libwrapper.

**Comment by fel-pt** [comment]
Everything looks fine here now :)
