### ISSUE TITLE
Conflicts with ZoomPanOptions and token-tooltip-alt

### ISSUE THREAD

**Issue by RollToSaveVsDragons** [David-Zvekic/TokensVisible#8]
ZoomPanOptions - does not zoom to cursor
token-tooltip-alt - does not display tooltips
https://github.com/itamarcu/ZoomPanOptions
https://github.com/bmarian/token-tooltip-alt

**Comment by David-Zvekic** [comment]
I can't replicate these problems.  Both modules seem to work the same whether or not I have TokensVisible installed.
tested on Foundry 0.7.10  system DnD5 1.2.4
